### ISSUE TITLE
Error: "Required parameter is missing: grant_type"

### ISSUE THREAD

**Issue by ghost** [raventools/dashing-google-analytics#1]
Hi, for the last couple of weeks I've been trying to create a dashboard using dashing.io, so for even though I have tried and read every bit of entry, I faced with different errors, the final error I get is;
/Users/oytune/Desktop/workspace/dashing/raventools-dashing-google-analytics-942709c/jobs/google_analytics.rb:20: warning: already initialized constant OpenSSL::SSL::VERIFY_PEER
#<TypeError: no implicit conversion of nil into String>
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on 0.0.0.0:3030, CTRL+C to stop
scheduler caught exception:
Authorization failed.  Server message:
{
  "error" : "invalid_request",
  "error_description" : "Required parameter is missing: grant_type"
}
/Library/Ruby/Gems/2.0.0/gems/signet-0.6.0/lib/signet/oauth_2/client.rb:947:in `fetch_access_token'
/Library/Ruby/Gems/2.0.0/gems/signet-0.6.0/lib/signet/oauth_2/client.rb:964:in `fetch_access_token!'
/Users/oytune/Desktop/workspace/dashing/raventools-dashing-google-analytics-942709c/jobs/google_analytics.rb:50:in `block in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/Library/Ruby/Gems/2.0.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/Library/Ruby/Gems/2.0.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/Library/Ruby/Gems/2.0.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
/Library/Ruby/Gems/2.0.0/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'

And the code leading this error is;

require 'google/api_client'
require 'date'
require 'openssl'

service_account_email = ENV['GOOGLE_SERVICE_ACCOUNT_EMAIL']
google_private_key = ENV['GOOGLE_PRIVATE_KEY']
google_private_key_secret = ENV['GOOGLE_PRIVATE_KEY_SECRET']
view_id = ENV['GOOGLE_ANALYTICS_VIEW_ID']

client = Google::APIClient.new(
  application_name: 'Dashing',
  application_version: '0.01'
)
begin

  OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE
  key = OpenSSL::PKey::RSA.new google_private_key, google_private_key_secret
  client.authorization = Signet::OAuth2::Client.new(
    token_credential_uri: 'https://accounts.google.com/o/oauth2/token',
    audience: 'https://accounts.google.com/o/oauth2/token',
    scope: 'https://www.googleapis.com/auth/analytics.readonly',
    issuer: service_account_email,
    signing_key: key
  )
rescue StandardError => e
  puts e.inspect
end

SCHEDULER.every '60m', first_in: 0 do

  client.authorization.fetch_access_token!
  analytics = client.discovered_api('analytics', 'v3')

  start_date = (DateTime.now - 31).strftime('%Y-%m-%d')
  start_date_display = DateTime.parse(start_date).strftime('%-m/%-d/%Y')
  end_date = (DateTime.now - 1).strftime('%Y-%m-%d')
  end_date_display = DateTime.parse(end_date).strftime('%-m/%-d/%Y')

  sessions = client.execute(
    api_method: analytics.data.ga.get, parameters: {
      'ids' => 'ga:' + view_id,
      'start-date' => start_date,
      'end-date' => end_date,
      'metrics' => 'ga:sessions'
    }
  )
  send_event(
    'ga_sessions',
    current: sessions.data.rows.count > 0 ? sessions.data.rows[0][0] : 0
  )

  new_sessions = client.execute(
    api_method: analytics.data.ga.get, parameters: {
      'ids' => 'ga:' + view_id,
      'start-date' => start_date,
      'end-date' => end_date,
      'metrics' => 'ga:sessions',
      'filters' => 'ga:userType==New Visitor'
    }
  )
  send_event(
    'ga_new_sessions',
    current: new_sessions.data.rows.count > 0 ? new_sessions.data.rows[0][0] : 0
  )

  traffic_sources = client.execute(
    api_method: analytics.data.ga.get, parameters: {
      'ids' => 'ga:' + view_id,
      'start-date' => start_date,
      'end-date' => end_date,
      'metrics' => 'ga:sessions',
      'dimensions' => 'ga:medium',
      'sort' => '-ga:sessions'
    }
  )

  traffic_sources_list = traffic_sources.data.rows.map do |row|
    row[0] = row[0][0...50] + ' ...' if row[0].length > 50
    {
      label: row[0],
      value: row[1]
    }
  end
  send_event(
    'ga_traffic_sources',
    items: traffic_sources.data.rows.count > 0 ? traffic_sources_list.take(10) : []
  )

  bounce_rate = client.execute(
    api_method: analytics.data.ga.get, parameters: {
      'ids' => 'ga:' + view_id,
      'start-date' => start_date,
      'end-date' => end_date,
      'metrics' => 'ga:bounceRate'
    }
  )
  send_event(
    'ga_bounce_rate',
    current: bounce_rate.data.rows.count > 0 ? bounce_rate.data.rows[0][0].to_f.round(2) : 0,
    suffix: '%'
  )

  (1..20).each do |goal_id|
    # Completions
    goal_completions = client.execute(
      api_method: analytics.data.ga.get, parameters: {
        'ids' => 'ga:' + view_id,
        'start-date' => start_date,
        'end-date' => end_date,
        'metrics' => "ga:goal#{goal_id}Completions"
      }
    )
    send_event(
      "ga_goal_#{goal_id}_completions",
      current: goal_completions.data.rows.count > 0 ? goal_completions.data.rows[0][0] : 0
    )

    goal_conversion_rate = client.execute(
      api_method: analytics.data.ga.get, parameters: {
        'ids' => 'ga:' + view_id,
        'start-date' => start_date,
        'end-date' => end_date,
        'metrics' => "ga:goal#{goal_id}ConversionRate"
      }
    )
    send_event(
      "ga_goal_#{goal_id}_conversion_rate",
      current: goal_conversion_rate.data.rows.count > 0 ? goal_conversion_rate.data.rows[0][0].to_f.round(2) : 0,
      suffix: '%'
    )

    goal_completions_dates = client.execute(
      api_method: analytics.data.ga.get, parameters: {
        'ids' => 'ga:' + view_id,
        'start-date' => start_date,
        'end-date' => end_date,
        'metrics' => "ga:goal#{goal_id}Completions",
        'dimensions' => 'ga:date'
      }
    )
    goal_completions_plot = []
    index = 0
    goal_completions_dates.data.rows.each do |row|
      goal_completions_plot << { x: index, y: row[1].to_i }
      index += 1
    end
    send_event(
      "ga_goal_#{goal_id}_completions_chart",
      points: goal_completions_dates.data.rows.count > 0 ? goal_completions_plot : [],
      moreinfo: "Chart: #{start_date_display} - #{end_date_display}"
    )
  end

  sessions_dates = client.execute(
    api_method: analytics.data.ga.get, parameters: {
      'ids' => 'ga:' + view_id,
      'start-date' => start_date,
      'end-date' => end_date,
      'metrics' => 'ga:sessions',
      'dimensions' => 'ga:date'
    }
  )
  sessions_dates_plot = []
  index = 0
  sessions_dates.data.rows.each do |row|
    sessions_dates_plot << { x: index, y: row[1].to_i }
    index += 1
  end
  send_event(
    'ga_session_chart',
    points: sessions_dates.data.rows.count > 0 ? sessions_dates_plot : [],
    moreinfo: "Chart: #{start_date_display} - #{end_date_display}"
  )
end

I have set the credentials in .env-dist file and of course, I created a compute engine service account on google analytics and tried both .json and .p12 key options non to be seen as working yet. I would appreciate any comments whether related with solution or leading me to quit trying to authenticate google analytics api.

Thanks in advance.

**Comment by ghost** [comment]
I would be so happy if @sqrrrl takes a look at this comment.

**Comment by sqrrrl** [comment]
Double check that your env variables are correct. The grant type is determined based on what fields are set. For service accounts, it's looking at issuer and signing_key (see https://github.com/google/signet/blob/master/lib/signet/oauth_2/client.rb#L839)

If you're using a vanilla service, account I suggest using the googleauth gem instead of signet directly. It's a wrapper, but makes a lot of these cases much simpler.

FYI - Please don't do:

```
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE
```

You're disabling a key part of TLS security by doing that.

**Comment by ghost** [comment]
@sqrrrl thank you for this quick reply. I have resolved it after a month. Required parameter error is I believe caused by lack of OAuth Consent. After creating service and the p12 key etc. I had to go OAuth Consent screen and simply set the application name and than while starting client application I set this application name on it. And it works. You are completely right about OpenSLL  it gives me errors while running but as you said, which I resolved as well. Now Ruby is up and running.

**Comment by SuperDuperOne** [comment]
Hi @sqrrrl - I'm also having issue with authenticating my service account user,
as it stands I have followed along with your READme and have extracted the p12 (and json) file to retrieve the "GOOGLE_PRIVATE_KEY" 

I have added the key into the .evn-dist

However I keep coming across this error message. 

> scheduler caught exception:
> Authorization failed.  Server message:
> {
>   "error": "unsupported_grant_type",
>   "error_description": "Invalid grant_type: "
> }

any suggestions/help would be great, 

thanks!
